In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Part 2 - Now let's make the ANN!

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 9, init = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(output_dim = 9, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 9, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 9, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 9, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 9, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 9, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 9, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 9, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 9, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 9, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 9, init = 'uniform', activation = 'relu'))
# Adding the output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 5, nb_epoch = 100)

# Part 3 - Making the predictions and evaluating the model

# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

Using TensorFlow backend.
c:\users\arbaz\anaconda\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:41: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=6, kernel_initializer="uniform", activation="relu", input_dim=11)`
c:\users\arbaz\anaconda\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:44: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", units=6, activation="relu")`
c:\users\arbaz\anaconda\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:45: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", units=6, activation="relu")`
c:\users\arbaz\anaconda\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:46: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", units=6, activation="relu")`
c:\users\arbaz\anaconda\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:47: UserWarning: Update your `Dense` call to the

Epoch 1/100
8000/8000 [==============================] - 3s 432us/step - loss: 0.4919 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 142us/step - loss: 0.4316 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 153us/step - loss: 0.4255 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 1s 147us/step - loss: 0.4199 - acc: 0.8211
Epoch 5/100
8000/8000 [==============================] - 1s 139us/step - loss: 0.4171 - acc: 0.8255
Epoch 6/100
8000/8000 [==============================] - 1s 143us/step - loss: 0.4152 - acc: 0.8301
Epoch 7/100
8000/8000 [==============================] - 1s 137us/step - loss: 0.4136 - acc: 0.8300
Epoch 8/100
8000/8000 [==============================] - 1s 138us/step - loss: 0.4125 - acc: 0.8317
Epoch 9/100
8000/8000 [==============================] - 1s 138us/step - loss: 0.4114 - acc: 0.8341
Epoch 10/100
8000/8000 [==============================] - 1s 146us/step - loss: 0.4111 - acc: 0.8334

8000/8000 [==============================] - 1s 127us/step - loss: 0.4017 - acc: 0.8336
Epoch 83/100
8000/8000 [==============================] - 1s 121us/step - loss: 0.4016 - acc: 0.8344
Epoch 84/100
8000/8000 [==============================] - 1s 127us/step - loss: 0.4016 - acc: 0.8349
Epoch 85/100
8000/8000 [==============================] - 1s 122us/step - loss: 0.4012 - acc: 0.8354
Epoch 86/100
8000/8000 [==============================] - 1s 123us/step - loss: 0.4020 - acc: 0.8351
Epoch 87/100
8000/8000 [==============================] - 1s 124us/step - loss: 0.4011 - acc: 0.8339
Epoch 88/100
8000/8000 [==============================] - 1s 120us/step - loss: 0.4011 - acc: 0.8351
Epoch 89/100
8000/8000 [==============================] - 1s 122us/step - loss: 0.4024 - acc: 0.8347
Epoch 90/100
8000/8000 [==============================] - 1s 120us/step - loss: 0.4014 - acc: 0.8366
Epoch 91/100
8000/8000 [==============================] - 1s 137us/step - loss: 0.4007 - acc: 0.8344
Epo

In [2]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)


In [3]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [4]:
cm

array([[1550,   45],
       [ 267,  138]], dtype=int64)

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Importing the dataset
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Part 2 - Now let's make the ANN!


In [6]:
import keras
from keras.models import Sequential
from keras.layers import Dense

# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 9, init = 'uniform', activation = 'relu', input_dim = 11))

# Adding the 11 hidden layer
classifier.add(Dense(output_dim = 9, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 9, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 9, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 9, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 9, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 9, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 9, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 9, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 9, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 9, init = 'uniform', activation = 'relu'))
classifier.add(Dense(output_dim = 9, init = 'uniform', activation = 'relu'))
# Adding the output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


c:\users\arbaz\anaconda\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:9: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(units=9, kernel_initializer="uniform", activation="relu", input_dim=11)`
  if __name__ == '__main__':
c:\users\arbaz\anaconda\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:12: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", units=9, activation="relu")`
  if sys.path[0] == '':
c:\users\arbaz\anaconda\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:13: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", units=9, activation="relu")`
  del sys.path[0]
c:\users\arbaz\anaconda\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:14: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(kernel_initializer="uniform", units=9, activation="relu")`
  
c:\users\arbaz\anaconda\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:1

In [10]:
classifier.fit(X_train, y_train, batch_size = 1, nb_epoch = 200)

Epoch 1/200
  62/8000 [..............................] - ETA: 17s - loss: 0.3567 - acc: 0.8226

c:\users\arbaz\anaconda\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


8000/8000 [==============================] - 12s 2ms/step - loss: 0.3498 - acc: 0.8586
Epoch 2/200
8000/8000 [==============================] - 13s 2ms/step - loss: 0.3464 - acc: 0.8611
Epoch 3/200
8000/8000 [==============================] - 13s 2ms/step - loss: 0.3463 - acc: 0.8611
Epoch 4/200
8000/8000 [==============================] - 12s 2ms/step - loss: 0.3453 - acc: 0.8624
Epoch 5/200
8000/8000 [==============================] - 12s 1ms/step - loss: 0.3489 - acc: 0.8594
Epoch 6/200
8000/8000 [==============================] - 13s 2ms/step - loss: 0.3455 - acc: 0.8596
Epoch 7/200
8000/8000 [==============================] - 14s 2ms/step - loss: 0.3453 - acc: 0.8608
Epoch 8/200
8000/8000 [==============================] - 14s 2ms/step - loss: 0.3440 - acc: 0.8625
Epoch 9/200
8000/8000 [==============================] - 14s 2ms/step - loss: 0.3447 - acc: 0.8626
Epoch 10/200
8000/8000 [==============================] - 14s 2ms/step - loss: 0.3453 - acc: 0.8605
Epoch 11/200
8000/800

8000/8000 [==============================] - 16s 2ms/step - loss: 0.3354 - acc: 0.8656
Epoch 84/200
8000/8000 [==============================] - 13s 2ms/step - loss: 0.3375 - acc: 0.8652
Epoch 85/200
8000/8000 [==============================] - 12s 2ms/step - loss: 0.3379 - acc: 0.8628
Epoch 86/200
8000/8000 [==============================] - 13s 2ms/step - loss: 0.3372 - acc: 0.8628
Epoch 87/200
8000/8000 [==============================] - 13s 2ms/step - loss: 0.3372 - acc: 0.8633
Epoch 88/200
8000/8000 [==============================] - 14s 2ms/step - loss: 0.3358 - acc: 0.8655
Epoch 89/200
8000/8000 [==============================] - 14s 2ms/step - loss: 0.3363 - acc: 0.8664
Epoch 90/200
8000/8000 [==============================] - 13s 2ms/step - loss: 0.3354 - acc: 0.8668
Epoch 91/200
8000/8000 [==============================] - 13s 2ms/step - loss: 0.3350 - acc: 0.8640
Epoch 92/200
8000/8000 [==============================] - 13s 2ms/step - loss: 0.3343 - acc: 0.8669
Epoch 93/200


8000/8000 [==============================] - 14s 2ms/step - loss: 0.3308 - acc: 0.8676
Epoch 165/200
8000/8000 [==============================] - 14s 2ms/step - loss: 0.3289 - acc: 0.8665
Epoch 166/200
8000/8000 [==============================] - 14s 2ms/step - loss: 0.3321 - acc: 0.8654
Epoch 167/200
8000/8000 [==============================] - 15s 2ms/step - loss: 0.3325 - acc: 0.8683
Epoch 168/200
8000/8000 [==============================] - 15s 2ms/step - loss: 0.3302 - acc: 0.8649
Epoch 169/200
8000/8000 [==============================] - 15s 2ms/step - loss: 0.3341 - acc: 0.8659
Epoch 170/200
8000/8000 [==============================] - 17s 2ms/step - loss: 0.3315 - acc: 0.8651
Epoch 171/200
8000/8000 [==============================] - 18s 2ms/step - loss: 0.3329 - acc: 0.8674
Epoch 172/200
8000/8000 [==============================] - 18s 2ms/step - loss: 0.3302 - acc: 0.8678
Epoch 173/200
8000/8000 [==============================] - 18s 2ms/step - loss: 0.3311 - acc: 0.8659
Epoc

In [8]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [9]:
cm

array([[1523,   72],
       [ 202,  203]], dtype=int64)

In [11]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [12]:
cm

array([[1486,  109],
       [ 184,  221]], dtype=int64)